port="8000"
dev = true

[database]
db_host="localhost"
# db_host="192.168.199.23"
db_port="27017"
db_schema_name="openseasync"
db_username="root"
# db_username="123456"
db_pwd="123456"
db_args="charset=utf8mb4&parseTime=True&loc=Local"
